version: '3.8'

services:
  statamic-app:
    build: .
    container_name: statamic_app
    user: "1000:1000"
    restart: unless-stopped
    volumes:
      - ./site:/var/www/html:Z
    networks:
      - web-stack

  statamic-web:
    image: nginx:alpine
    container_name: statamic_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html:ro,Z
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z
    depends_on:
      - statamic-app
    networks:
      - web-stack

networks:
  web-stack:
    external: true
