title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: excerpt
            field:
              type: textarea
              display: Excerpt
              instructions: Brief project summary
          -
            handle: client_sector
            field:
              type: select
              display: Client Sector
              options:
                finance: Finance
                manufacturing: Manufacturing
                healthcare: Healthcare
                education: Higher Education
                public: Public Sector
          -
            handle: tech_stack
            field:
              type: tags
              display: Tech Stack
          -
            handle: project_role
            field:
              type: text
              display: Project Role
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true